1) create a list, accept 5 numbers , store them in the list and finally convert that list to numpy array.

2) create numpy array of 5 numbers and print their sum

3) create numpy double dimension array of 3*3 to store your initial and display them in a tabular form.

4) create one-d numpy array of 12 elements , accept 12 numbers and display them. Now convert this one-d array into (4*3) two-d array and display it in a tabular form.

5) create two double dimension array and arrange (stack) them using "axis=0" "axis=1" and  "axis=2".


6) create two one-d arrays and then find out:
	a) common elements of both the array
	b) unique elements of first array
	c) unique elements of second array

7) accept no.of rows and no. of cols from the user , create two-d array accordingly. Now calculate the sum as per "axis=0" and "axis=1"

8) declare two 2d arrays and calculate the sum as per "axis=0" "axis=1" and "axis=2"

9) create two-d array ,display it. Now accept a number from user and perform all arithmetic operations on each and every element of the array using that number.


10) accept start, end and how many numbers to be generated and then using "linspace" create numpy array.
11) create one-d array of 8 numbers and then using "slicing" concept,
	a) print numbers from 1 to 4
	b) print all the numbers from 3rd position
	c) print last 3 numbers

12) create 2 d array (4*3) with following values:
[[10,20,30,40],[50,60,70,80],[90,100,110,120]]

now using array slicing concept display following values
	a) display   50  60  70  80
	b) display 100 and 110
	c) display 30 70 and 110
	d) display 50  60  90 and 100


1) create a list, accept 5 numbers , store them in the list and finally convert that list to numpy array.

In [4]:
import numpy as np
list=[]
for i in range(5):
    num=int(input("enter the number: "))
    list.append(num)
print(list)
first=np.array(list)
print(list)

2) create numpy array of 5 numbers and print their sum


In [3]:
import numpy as np
first=np.array([21,22,23,24,25])
print(first)
second=np.sum(first)
print(second)


[21 22 23 24 25]
115


3) create numpy double dimension array of 3*3 to store your initial and display them in a tabular form.

In [10]:
import numpy as np
first=np.arange(10,91,10).reshape(3,3)
print(first)
second=tuple(map(tuple,first))
print(second)
third=list(map(list,first))
print(third)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
((10, 20, 30), (40, 50, 60), (70, 80, 90))
[[10, 20, 30], [40, 50, 60], [70, 80, 90]]


4) create one-d numpy array of 12 elements , accept 12 numbers and display them. Now convert this one-d array into (4*3) two-d array and display it in a tabular form.

In [15]:
import numpy as np
first=np.random.randint(20,100,12)
print(first)
first.shape=(4,3)
print(first)
second=tuple(map(tuple,first))
print(second)

[66 64 41 39 29 20 37 81 48 61 37 63]
[[66 64 41]
 [39 29 20]
 [37 81 48]
 [61 37 63]]
((66, 64, 41), (39, 29, 20), (37, 81, 48), (61, 37, 63))


5) create two double dimension array and arrange (stack) them using "axis=0" "axis=1" and  "axis=2"

In [16]:
import  numpy as np
first=np.array([[1,2,3],[3,4,5]])
second=np.array([[7,8,9],[10,12,13]])
third=np.stack((first,second),axis=0)
print(third)
fourth=np.stack((first,second),axis=1)
print(fourth)
fifth=np.stack((first,second),axis=2)
print(fifth)



[[[ 1  2  3]
  [ 3  4  5]]

 [[ 7  8  9]
  [10 12 13]]]
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 3  4  5]
  [10 12 13]]]
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 3 10]
  [ 4 12]
  [ 5 13]]]


6) create two one-d arrays and then find out:
	a) common elements of both the array
	b) unique elements of first array
	c) unique elements of second array

In [22]:
import numpy as np
first=np.array([1,2,3,4,5])
second=np.array([6,7,4,9,1])
third=np.intersect1d(first,second)
print(third)
print("***************")
forth=np.unique(first)
print(forth)
print("***************")
fifth=np.unique(second)
print(fifth)
print("***************")
sixth=np.setdiff1d(first,second)
print(sixth)

[1 4]
***************
[1 2 3 4 5]
***************
[1 4 6 7 9]
***************
[2 3 5]


7) accept no.of rows and no. of cols from the user , create two-d array accordingly. Now calculate the sum as per "axis=0" and "axis=1"

In [ ]:
import numpy as np
rownum=int(input("enter the rows"))
colnum=int(input("enter the colunm"))
first=np.random.randint(1,100,size=(rownum,colnum))
print(first)
second=np.sum(first,axis=0)
print(second)
third=np.sum(first,axis=1)
print(third)

8) declare two 2d arrays and calculate the sum as per "axis=0" "axis=1" and "axis=2"


In [23]:
import numpy as np
first=np.array([[1,2,3,4,5],[6,7,8,9,10]])
second=np.array([[10,20,30,40,50],[60,70,80,90,10]])
print(first)
print(second)
third=np.sum((first,second),axis=0)
print(third)
forth=np.sum((first,second),axis=1)
print(forth)
fifth=np.sum((first,second),axis=2)
print(fifth)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[10 20 30 40 50]
 [60 70 80 90 10]]
[[11 22 33 44 55]
 [66 77 88 99 20]]
[[  7   9  11  13  15]
 [ 70  90 110 130  60]]
[[ 15  40]
 [150 310]]


10) accept start, end and how many numbers to be generated and then using "linspace" create numpy array.

In [24]:
import  numpy as np
first=np.linspace(30,35,num=10)
print(first)


[30.         30.55555556 31.11111111 31.66666667 32.22222222 32.77777778
 33.33333333 33.88888889 34.44444444 35.        ]


11) create one-d array of 8 numbers and then using "slicing" concept,
	a) print numbers from 1 to 4
	b) print all the numbers from 3rd position
	c) print last 3 numbers

In [25]:
import numpy as np
first=np.array([1,2,3,4,5,6,7,8])
print(first)
second=first[1:5]
print(second)
third=first[3:]
print(third)
forth=first[-3:]
print(forth)

[1 2 3 4 5 6 7 8]
[2 3 4 5]
[4 5 6 7 8]
[6 7 8]


12) create 2 d array (4*3) with following values:
[[10,20,30,40],[50,60,70,80],[90,100,110,120]]

now using array slicing concept display following values
	a) display   50  60  70  80
	b) display 100 and 110
	c) display 30 70 and 110
	d) display 50  60  90 and 100

In [35]:
import numpy as np
first=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print(first)
print("************************")
second=first[1:2]
print(second)
print("************************")
third=first[2:3,1:3]
print(third)
print("************************")
forth=first[:,2:3]
print(forth)
print("************************")
fifth=first[1:3,:2]
print(fifth)


[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
************************
[[50 60 70 80]]
************************
[[100 110]]
************************
[[ 30]
 [ 70]
 [110]]
************************
[[ 50  60]
 [ 90 100]]
